name: wishlist
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Pour la connexion / signup
  shared_preferences: ^2.2.2

  # Pour SQLite
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0  # ğŸ†• Pour les requÃªtes HTTP
  flutter_secure_storage: ^9.0.0  # ğŸ†• Pour stocker le token

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



  # Assets (images, JSON, etc.)
  # assets:
  #   - assets/images/

  # Fonts (optionnel)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
